version: "3.9"

services:
  autonotes:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API=http://localhost:11434/api/chat
      - LLM_MODEL=deepseek-r1:14b
      - WHISPER_MODEL_DIR=/app/models/whisper
    volumes:
      - .:/app
      - whisper-models:/app/models/whisper
    restart: unless-stopped

volumes:
  whisper-models:
